set(EXTLIB_COMPILER_ARGS)
if(CMAKE_TOOLCHAIN_FILE)
    list(APPEND EXTLIB_COMPILER_ARGS
        "-DCMAKE_TOOLCHAIN_FILE:FILEPATH=${CMAKE_TOOLCHAIN_FILE}")
endif()
if(CMAKE_CXX_COMPILER_ID)
    list(APPEND EXTLIB_COMPILER_ARGS
        "-DCMAKE_CXX_COMPILER_ID:STRING=${CMAKE_CXX_COMPILER_ID}")
endif()
if(CMAKE_CXX_COMPILER)
    list(APPEND EXTLIB_COMPILER_ARGS
        "-DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}")
endif()
if(CMAKE_C_COMPILER_ID)
    list(APPEND EXTLIB_COMPILER_ARGS
        "-DCMAKE_C_COMPILER_ID:STRING=${CMAKE_C_COMPILER_ID}")
endif()
if(CMAKE_C_COMPILER)
    list(APPEND EXTLIB_COMPILER_ARGS
        "-DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}")
endif()
if(CMAKE_C_FLAGS)
    list(APPEND EXTLIB_COMPILER_ARGS
        "-DCMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}")
endif()
if(CMAKE_CXX_FLAGS)
    list(APPEND EXTLIB_COMPILER_ARGS
        "-DCMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS}")
endif()
